// January 30, 2023

#include <iostream>
using namespace std;

int main(){

// FIND LONGEST SUBSEQUENCE (ORDERED SUBSTRING) THAT IS A PALINDROME
// AND SUBTRACT IT'S LENGTH FROM ORIGINAL LENGTH OF STRING
// THIS GIVES NUMBER OF CHARS YOU'LL HAVE TO ADD AT DIFFERENT PLACES
// TO MAKE THE STRING A PALINDROME

    return 0;
}